---
abstract: 'Speedy functions to manipulate biological data'
author:
  - 'Joachim Bargsten <jwb@cpan.org>'
build_requires:
  Module::Build: 0.3601
  Test::More: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bio-Gonzales
recommends:
  Bio::Root::Version: 0
  Excel::Writer::XLSX: 0
  Net::DNS: 0
  Net::Domain: 0
  SVG: 0
  Term::ReadKey: 0
requires:
  Capture::Tiny: 0
  Config::General: 0
  Cwd: 0
  Data::Dumper: 0
  Data::Printer: 0
  Data::Visitor::Callback: 0
  DateTime: 0
  Digest::MD5: 0
  Digest::SHA1: 0
  File::Copy: 0
  File::Find: 0
  File::Path: 0
  File::Slurp: 0
  File::Spec: 0
  File::Temp: 0
  File::Touch: 0
  File::Which: 0
  Getopt::Long::Descriptive: 0
  HTTP::Date: 0
  IO::Prompt::Tiny: 0
  IO::Scalar: 0
  JSON::XS: 0
  List::MoreUtils: 0
  Math::Combinatorics: 0
  Moo: 0
  Mouse: 0
  MouseX::Foreign: 0
  Number::Format: 0
  Params::Util: 0
  Path::Class: 0
  Scalar::Util::Numeric: 0
  Set::IntervalTree: 0
  Storable: 0
  String::ShellQuote: 0
  Try::Tiny: 0
  URI: 0
  YAML::XS: 0
  constant: 0
  perl: 5.010
version: 0.0545
